[package]
name = "hackles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hackles"
path = "src/hackles.rs"

[lib]
name = "hackles_earley"
path = "src/lib/earley.rs"

[dependencies]
smol_str = "0.1"
# pest = "2.1"
# pest_derive = "2.1"